version: 2.1

executors:
  docker-publisher:
    docker:
      - image: docker:19
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

jobs:
  checkout_code:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: List Files
          command: |
            pwd
            ls -al
      - checkout
      - run:
          name: List Files
          command: |
            pwd
            ls -al
      # 持久化root目录
      - persist_to_workspace:
          root: /root
          paths:
            - project


  tag_release_image:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /root
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build & Push Image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            chmod +x $(pwd)/projector-server/gradlew
            DOCKER_BUILDKIT=1 docker build --progress=plain --build-arg buildGradle=true --build-arg downloadUrl=https://download.jetbrains.com/python/pycharm-community-$CIRCLE_TAG.tar.gz -f $(pwd)/Dockerfile -t 1995chen/pycharm-docker:$CIRCLE_TAG $(pwd)
            docker push 1995chen/pycharm-docker:$CIRCLE_TAG

workflows:
  production:
    jobs:
      - checkout_code:
          # this yaml anchor is setting these values to "filters-production"
          filters: &filters-production
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - tag_release_image:
          requires:
            - checkout_code
          context:
            - docker-hub-creds
          filters:
            <<: *filters-production